
###
POST http://localhost:3001/users
Content-Type:application/json

{
      "name":"abc",
      "gender":"abc",
      "phone":9813832136,
      "email":"abc@abc.com",
      "address":"abc",
      "nationality":"abc",
      "dob":"2001/10/12",
      "education":"abc",
      "modeOfContact":"abc"
}


###


###

GET http://localhost:3001/users

###