###
POST http://localhost:3001/products
Content-Type: application/json

{
    "title":"TEST 3",
    "description":"TEST DESC 3",
    "price":"123456789"
}


###

GET http://localhost:3001/products


###

GET http://localhost:3001/products/Fri Mar 26 2021 15:30:47 GMT+0545 (Nepal Time)0.031957119345608964

###
POST http://localhost:3001/users
Content-Type: application/json

{
      "name":"abc",
      "gender":"abc",
      "phone":"abc",
      "email":"abc",
      "address":"abc",
      "nationality":"abc",
      "dob":"abc",
      "education":"abc",
      "modeOfContact":"abc"
}


###


###

GET http://localhost:3001/users


###